version: "3.9"
services:
  deploy:
    container_name: java14app2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localPostgresSQLDB2:5432/local_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      java14-network:
        aliases:
            - java14app
networks:
  java14-network:
    name: 'our_java14_network'
